"""Added falculty_specialties table

Revision ID: 59335102e78a
Revises: 
Create Date: 2025-10-06 11:51:40.299689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59335102e78a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_specialties',
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('faculty_id', 'specialty_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faculty_specialties')
    # ### end Alembic commands ###
